name: 'Terraform - Docs'
#description: Run Terraform Plan and if successful, run Terraform Apply
#branding:
#  icon: filter
#  color: purple

jobs:
  tf-doc:
    steps:
    ## Check if GitHub runner is Linux, exit if it isn't
    - name: Check Runner is Linux
      if: runner.os != 'Linux'
      run: |
        echo "The operating system on the runner is not Linux, it's $RUNNER_OS."
        exit 1
      continue-on-error: false

    ## Greetings
    - name: Greetings
      run: echo "GitHub Runner running as ${GITHUB_ACTOR} on repo:${GITHUB_REPOSITORY} with ${RUNNER_OS}!"
   
    ## Harden runner
##    - name: Harden Runner
##      uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
##     with:
##       egress-policy: audit

    ## Login
    - name: OIDC Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_FEDERATION_CLIENT_ID }}
        tenant-id: ${{ secrets.ARM_TENANT_ID }}
        subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        enable-AzPSSession: true
        
    ## Checkout the repository
    - name: Clone Repo ${GITHUB_REPOSITORY}
      uses: actions/checkout@v4

    ## Install and setup Terraform
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false

    ## Show Terraform version
    - name: Show Terraform Version
      run: terraform -chdir=$TERRAFORM_WORKING_DIRECTORY version
  
  terraform-docs:
    ## Call reusable workflow
    uses: webstean/github-reusable-workflows/.github/workflows/tf-docs-reusable.yml@main
    with:
      target: ${{ matrix.target }}
