name: 'Terraform Docs'
#description: Run Terraform Plan and if successful, run Terraform Apply
#branding:
#  icon: filter
#  color: purple

on:
  push:
    branches:
    - main
    paths:
      - 'src/terraform/**'
      - '.github/workflows/**'
  pull_request:
    branches:
    - main
    paths:
      - 'src/terraform/**'
      - '.github/workflows/**'

##Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: read
  pull-requests: write

#These environment variables are used by the terraform azure provider to setup OIDC authenticate. 
env:
  WORKING_DIRECTORY: "./src/terraform"
  ## WORKING_DIRECTORY: "${{ vars.TERRAFORM_WORKING_DIRECTORY }}"
  APPLICATION_NAME: "aztftest"
  ENVIRONMENT_NAME: "production"    
  ## ENVIRONMENT_NAME: "staging"    
  ## ENVIRONMENT_NAME: "development"    
   ## OIDC Identity
  ARM_CLIENT_ID: "${{ secrets.AZURE_FEDERATION_CLIENT_ID }}"
  ## only needed for Service Principal
  #ARM_CLIENT_SECRET: "${{ secrets.ARM_CLIENT_SECRET }}"

  ARM_SUBSCRIPTION_ID: "${{ secrets.ARM_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.ARM_TENANT_ID }}"
  ARM_SKIP_PROVIDER_REGISTRATION: true
  
jobs:
  matrix-setup:
    name: 'Config Runner'
    strategy:
      matrix:
        ## runs-on: [ubuntu-latest, macos-latest, windows-latest]
        runs-on: [ubuntu-latest]
    runs-on: ${{ matrix.runs-on }}
    outputs:
      tfplanExitCode: ${{ steps.tf-planapply.outputs.exitcode }}

azure-logon:
    ## Call reusable workflow
    uses: webstean/github-reusable-workflows/.github/workflows/github-action-reuse-azure-logon.yml@main
    with:
      target: ${{ matrix.target }}

terraform-setup:
    ## Call reusable workflow
    uses: webstean/github-reusable-workflows/.github/workflows/github-action-reuse-tf-setup.yml@main
    with:
      target: ${{ matrix.target }}

terraform-planapply:
    ## Call reusable workflow
    uses: webstean/github-reusable-workflows/.github/workflows/github-action-reuse-tf-planapply.yml@main
    with:
      target: ${{ matrix.target }}
