name: Terraform - Run Plan / Apply for Terraform with OIDC logon

on:
  [workflow_dispatch]
  ##push:
  ##  branches:
  ##  - main
  ##  paths:
  ##    - 'src/terraform/**'
  ##    - '.github/workflows/**'
  ### pull_request:
  ###  branches:
  ###  - main
  ###  paths:
  ###    - 'src/terraform/**'
  ###    - '.github/workflows/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  
permissions:
      id-token: write
      contents: read

jobs:
  oidc:
    strategy:
      matrix:
        ## runs-on: [ubuntu-latest, macos-latest, windows-latest]
        runs-on: [ubuntu-latest]
    runs-on: ${{ matrix.runs-on }}

    steps:
    - name: OIDC Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_FEDERATION_CLIENT_ID }}
        tenant-id: ${{ secrets.ARM_TENANT_ID }}
        subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        enable-AzPSSession: true
        
    - name: Run Terraform Plan / Apply
      uses: webstean/github-reusable-workflows/workflows/tf-apply-reusable.txt@main
      with:
        target: ${{ matrix.target }}